<x-moonshine::box
    :title="$decoration->label()"
>
    <x-moonshine::resource-renderable
        :components="$decoration->getFields()"
        :item="$item"
        :resource="$resource"
    />
</x-moonshine::box>
